//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuronExportedDocuments.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuronExportedDocuments.Resources.IdentityResources", typeof(IdentityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string rs_AccessDeniedCaption {
            get {
                return ResourceManager.GetString("rs_AccessDeniedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have rights to acces te page. &lt;br/&gt; For more information contact with our support: {0}.
        /// </summary>
        public static string rs_AccessDeniedMessage {
            get {
                return ResourceManager.GetString("rs_AccessDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your {0} account..
        /// </summary>
        public static string rs_AssociateYourProviderAccount {
            get {
                return ResourceManager.GetString("rs_AssociateYourProviderAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Form.
        /// </summary>
        public static string rs_AssociationForm {
            get {
                return ResourceManager.GetString("rs_AssociationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected user already had a role..
        /// </summary>
        public static string rs_CantSetNewRoleForUserWithRoles {
            get {
                return ResourceManager.GetString("rs_CantSetNewRoleForUserWithRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string rs_CheckEmailForPass {
            get {
                return ResourceManager.GetString("rs_CheckEmailForPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in.
        /// </summary>
        public static string rs_ClickHereToLogIn {
            get {
                return ResourceManager.GetString("rs_ClickHereToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmAccount.
        /// </summary>
        public static string rs_ConfirmAccount {
            get {
                return ResourceManager.GetString("rs_ConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your account. Please {0}.
        /// </summary>
        public static string rs_ConfirmationThanks {
            get {
                return ResourceManager.GetString("rs_ConfirmationThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by clicking &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        public static string rs_ConfirmEmailBody {
            get {
                return ResourceManager.GetString("rs_ConfirmEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your account.
        /// </summary>
        public static string rs_ConfirmEmailTitle {
            get {
                return ResourceManager.GetString("rs_ConfirmEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s admin role can&apos;t be deleted. There are must be a one user with the admin role.
        /// </summary>
        public static string rs_DeleteRolesCantDeleteLastAdmin {
            get {
                return ResourceManager.GetString("rs_DeleteRolesCantDeleteLastAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Roles are Deleted.
        /// </summary>
        public static string rs_DeleteRolesSuccess {
            get {
                return ResourceManager.GetString("rs_DeleteRolesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all user&apos;s roles.
        /// </summary>
        public static string rs_DeleteUserRolesToolTip {
            get {
                return ResourceManager.GetString("rs_DeleteUserRolesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with &lt;strong&gt;{0}&lt;/strong&gt;.
        ///            Please enter a user name for this site below and click the Register button to finish
        ///            logging in..
        /// </summary>
        public static string rs_ExternalAuthentificationSuccess {
            get {
                return ResourceManager.GetString("rs_ExternalAuthentificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string rs_ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("rs_ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string rs_ForgotYourPasswordQuestion {
            get {
                return ResourceManager.GetString("rs_ForgotYourPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string rs_IdentityConfirmNewPassword {
            get {
                return ResourceManager.GetString("rs_IdentityConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string rs_IdentityConfirmPassCompareValidationMessage {
            get {
                return ResourceManager.GetString("rs_IdentityConfirmPassCompareValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string rs_IdentityConfirmPassValidationMessage {
            get {
                return ResourceManager.GetString("rs_IdentityConfirmPassValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string rs_IdentityConfirmPassword {
            get {
                return ResourceManager.GetString("rs_IdentityConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string rs_IdentityCurrentPassword {
            get {
                return ResourceManager.GetString("rs_IdentityCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string rs_IdentityEmail {
            get {
                return ResourceManager.GetString("rs_IdentityEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string rs_IdentityErrorOccurred {
            get {
                return ResourceManager.GetString("rs_IdentityErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was removed..
        /// </summary>
        public static string rs_IdentityExternalLoginRemoved {
            get {
                return ResourceManager.GetString("rs_IdentityExternalLoginRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string rs_IdentityInvalidUserNameOrPass {
            get {
                return ResourceManager.GetString("rs_IdentityInvalidUserNameOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string rs_IdentityNewPassValidationLengthMessage {
            get {
                return ResourceManager.GetString("rs_IdentityNewPassValidationLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string rs_IdentityNewPassword {
            get {
                return ResourceManager.GetString("rs_IdentityNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string rs_IdentityPassChanged {
            get {
                return ResourceManager.GetString("rs_IdentityPassChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string rs_IdentityPassIsSet {
            get {
                return ResourceManager.GetString("rs_IdentityPassIsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string rs_IdentityPassword {
            get {
                return ResourceManager.GetString("rs_IdentityPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string rs_IdentityRememberMe {
            get {
                return ResourceManager.GetString("rs_IdentityRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user either does not exist or is not confirmed..
        /// </summary>
        public static string rs_IdentityUserIsNotConfirmed {
            get {
                return ResourceManager.GetString("rs_IdentityUserIsNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found..
        /// </summary>
        public static string rs_IdentityUserNotFound {
            get {
                return ResourceManager.GetString("rs_IdentityUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string rs_LogIn {
            get {
                return ResourceManager.GetString("rs_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure.
        /// </summary>
        public static string rs_LoginFailure {
            get {
                return ResourceManager.GetString("rs_LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account.
        /// </summary>
        public static string rs_ManageAccount {
            get {
                return ResourceManager.GetString("rs_ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string rs_Register {
            get {
                return ResourceManager.GetString("rs_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string rs_RegisterNewUser {
            get {
                return ResourceManager.GetString("rs_RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please {0}.
        /// </summary>
        public static string rs_ResetPassAndLogIn {
            get {
                return ResourceManager.GetString("rs_ResetPassAndLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by clicking &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        public static string rs_ResetPassBody {
            get {
                return ResourceManager.GetString("rs_ResetPassBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string rs_ResetPassTitle {
            get {
                return ResourceManager.GetString("rs_ResetPassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string rs_ResetPassword {
            get {
                return ResourceManager.GetString("rs_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string rs_ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("rs_ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting of the admin role was failed.
        /// </summary>
        public static string rs_SetAdminRoleError {
            get {
                return ResourceManager.GetString("rs_SetAdminRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The admin role is set for the user..
        /// </summary>
        public static string rs_SetAdminRoleSucess {
            get {
                return ResourceManager.GetString("rs_SetAdminRoleSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the user as Admin.
        /// </summary>
        public static string rs_SetAdminUserRolesToolTip {
            get {
                return ResourceManager.GetString("rs_SetAdminUserRolesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting of the SyncService role was failed.
        /// </summary>
        public static string rs_SetSyncServiceRoleError {
            get {
                return ResourceManager.GetString("rs_SetSyncServiceRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SyncService role is set for the user..
        /// </summary>
        public static string rs_SetSyncServiceRoleSucess {
            get {
                return ResourceManager.GetString("rs_SetSyncServiceRoleSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the user as SyncService.
        /// </summary>
        public static string rs_SetSyncUserRolesToolTip {
            get {
                return ResourceManager.GetString("rs_SetSyncUserRolesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string rs_TryAgainCaption {
            get {
                return ResourceManager.GetString("rs_TryAgainCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with service..
        /// </summary>
        public static string rs_UnsuccessfulLoginWithService {
            get {
                return ResourceManager.GetString("rs_UnsuccessfulLoginWithService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string rs_UseLocalAccount {
            get {
                return ResourceManager.GetString("rs_UseLocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not found.
        /// </summary>
        public static string rs_UserNotFound {
            get {
                return ResourceManager.GetString("rs_UserNotFound", resourceCulture);
            }
        }
    }
}
