//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuronExportedDocuments.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuronExportedDocuments.Resources.MainExceptionMessages", typeof(MainExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant Find the Document for the Operation.
        /// </summary>
        public static string rs_CantFindTheDocumentForOperation {
            get {
                return ResourceManager.GetString("rs_CantFindTheDocumentForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document, which info wasn&apos;t sent to user, is not been able to Republish..
        /// </summary>
        public static string rs_CantRepublishDocument {
            get {
                return ResourceManager.GetString("rs_CantRepublishDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t convert the exported document with Neuron ID {0}..
        /// </summary>
        public static string rs_DocumentConvertError {
            get {
                return ResourceManager.GetString("rs_DocumentConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Document&apos;s credentials wasn&apos;t sended to user..
        /// </summary>
        public static string rs_DocumentInfoWasntSendedToUser {
            get {
                return ResourceManager.GetString("rs_DocumentInfoWasntSendedToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Ip Address : .
        /// </summary>
        public static string rs_DocumentLogOperationConnectionIpAddress {
            get {
                return ResourceManager.GetString("rs_DocumentLogOperationConnectionIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info : .
        /// </summary>
        public static string rs_DocumentLogOperationInfo {
            get {
                return ResourceManager.GetString("rs_DocumentLogOperationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Date : .
        /// </summary>
        public static string rs_DocumentLogOperationOperationDate {
            get {
                return ResourceManager.GetString("rs_DocumentLogOperationOperationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationType : .
        /// </summary>
        public static string rs_DocumentLogOperationOperationType {
            get {
                return ResourceManager.GetString("rs_DocumentLogOperationOperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceDocument Id : .
        /// </summary>
        public static string rs_DocumentLogOperationServiceDocumentId {
            get {
                return ResourceManager.GetString("rs_DocumentLogOperationServiceDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Document wasn&apos;t archived.
        /// </summary>
        public static string rs_DocumentWasntArchived {
            get {
                return ResourceManager.GetString("rs_DocumentWasntArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Document was not published..
        /// </summary>
        public static string rs_DocumentWasntPublished {
            get {
                return ResourceManager.GetString("rs_DocumentWasntPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Document was not republished..
        /// </summary>
        public static string rs_DocumentWasntRePublished {
            get {
                return ResourceManager.GetString("rs_DocumentWasntRePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Path : .
        /// </summary>
        public static string rs_ErrorInPath {
            get {
                return ResourceManager.GetString("rs_ErrorInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception For OperationLog:
        ///{1}
        ///in Document:
        ///{0}.
        /// </summary>
        public static string rs_ExceptionForOperationLog {
            get {
                return ResourceManager.GetString("rs_ExceptionForOperationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t publish documents..
        /// </summary>
        public static string rs_ExceptionInDocumentPublisherControllerGet {
            get {
                return ResourceManager.GetString("rs_ExceptionInDocumentPublisherControllerGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t import document..
        /// </summary>
        public static string rs_ExceptionInImportControllerPost {
            get {
                return ResourceManager.GetString("rs_ExceptionInImportControllerPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document with Neuron ID {0} doesn&apos;t have any data. Imoprt is canceled..
        /// </summary>
        public static string rs_ExportServiceDocumentHasNoData {
            get {
                return ResourceManager.GetString("rs_ExportServiceDocumentHasNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All atempts for generetating Document ID is over..
        /// </summary>
        public static string rs_GeneratingIdAttemptsOutOfBounds {
            get {
                return ResourceManager.GetString("rs_GeneratingIdAttemptsOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message : .
        /// </summary>
        public static string rs_Message {
            get {
                return ResourceManager.GetString("rs_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Url : .
        /// </summary>
        public static string rs_RawUrl {
            get {
                return ResourceManager.GetString("rs_RawUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors found during &quot;Send by email&quot; process..
        /// </summary>
        public static string rs_SendEmailError {
            get {
                return ResourceManager.GetString("rs_SendEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuron Db Document Id :.
        /// </summary>
        public static string rs_ServiceDocumenNeuronDbDocumentId {
            get {
                return ResourceManager.GetString("rs_ServiceDocumenNeuronDbDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : .
        /// </summary>
        public static string rs_ServiceDocumenStatus {
            get {
                return ResourceManager.GetString("rs_ServiceDocumenStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Document Name : .
        /// </summary>
        public static string rs_ServiceDocumentName {
            get {
                return ResourceManager.GetString("rs_ServiceDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source : .
        /// </summary>
        public static string rs_Source {
            get {
                return ResourceManager.GetString("rs_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace : .
        /// </summary>
        public static string rs_StackTrace {
            get {
                return ResourceManager.GetString("rs_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetSite : .
        /// </summary>
        public static string rs_TargetSite {
            get {
                return ResourceManager.GetString("rs_TargetSite", resourceCulture);
            }
        }
    }
}
