//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuronExportedDocuments.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuronExportedDocuments.Resources.MainMessages", typeof(MainMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        public static string rs_AdminPanel {
            get {
                return ResourceManager.GetString("rs_AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose document format:.
        /// </summary>
        public static string rs_ChooseDocumentFormat {
            get {
                return ResourceManager.GetString("rs_ChooseDocumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string rs_Close {
            get {
                return ResourceManager.GetString("rs_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your document will be acessiable until.
        /// </summary>
        public static string rs_DocumentAccessibilityTerm {
            get {
                return ResourceManager.GetString("rs_DocumentAccessibilityTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Code.
        /// </summary>
        public static string rs_DocumentPublishId {
            get {
                return ResourceManager.GetString("rs_DocumentPublishId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string rs_DocumentPublishPassword {
            get {
                return ResourceManager.GetString("rs_DocumentPublishPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Neuron document.
        /// </summary>
        public static string rs_DownloadNeuronDocument {
            get {
                return ResourceManager.GetString("rs_DownloadNeuronDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        public static string rs_EditServiceIsDefaultName {
            get {
                return ResourceManager.GetString("rs_EditServiceIsDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service Message.
        /// </summary>
        public static string rs_EditServiceMessageCaption {
            get {
                return ResourceManager.GetString("rs_EditServiceMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string rs_EditServiceMessageName {
            get {
                return ResourceManager.GetString("rs_EditServiceMessageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formater Keys.
        /// </summary>
        public static string rs_FormaterKeysName {
            get {
                return ResourceManager.GetString("rs_FormaterKeysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get.
        /// </summary>
        public static string rs_GetDocument {
            get {
                return ResourceManager.GetString("rs_GetDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF file.
        /// </summary>
        public static string rs_GetDocumentAsPdf {
            get {
                return ResourceManager.GetString("rs_GetDocumentAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string rs_GetDocumentAsPng {
            get {
                return ResourceManager.GetString("rs_GetDocumentAsPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images archive.
        /// </summary>
        public static string rs_GetDocumentAsZip {
            get {
                return ResourceManager.GetString("rs_GetDocumentAsZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a Neuron document.
        /// </summary>
        public static string rs_GetNeuronDocument {
            get {
                return ResourceManager.GetString("rs_GetNeuronDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get next document.
        /// </summary>
        public static string rs_GetNextDocument {
            get {
                return ResourceManager.GetString("rs_GetNextDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string rs_Page {
            get {
                return ResourceManager.GetString("rs_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document_{0}.pdf.
        /// </summary>
        public static string rs_PDFDocumentDefaultName {
            get {
                return ResourceManager.GetString("rs_PDFDocumentDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document_{0}.png.
        /// </summary>
        public static string rs_PNGDocumentDefaultName {
            get {
                return ResourceManager.GetString("rs_PNGDocumentDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for the Document ID: &quot;{0}&quot; with wrong password from IP: &quot;{1}&quot;.
        /// </summary>
        public static string rs_RequestForDocumentWithWrongPassword {
            get {
                return ResourceManager.GetString("rs_RequestForDocumentWithWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for an unexisted document with ID: &quot;{0}&quot;  from IP: &quot;{1}&quot;.
        /// </summary>
        public static string rs_RequestForUnexistedDocument {
            get {
                return ResourceManager.GetString("rs_RequestForUnexistedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string rs_Save {
            get {
                return ResourceManager.GetString("rs_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string rs_Search {
            get {
                return ResourceManager.GetString("rs_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        public static string rs_ServiceMessageIsDefaultDisplayName {
            get {
                return ResourceManager.GetString("rs_ServiceMessageIsDefaultDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Key.
        /// </summary>
        public static string rs_ServiceMessageKeyDisplayName {
            get {
                return ResourceManager.GetString("rs_ServiceMessageKeyDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string rs_ServiceMessageMessageDisplayName {
            get {
                return ResourceManager.GetString("rs_ServiceMessageMessageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuron Documents Service Messages.
        /// </summary>
        public static string rs_ServiceMessagesList {
            get {
                return ResourceManager.GetString("rs_ServiceMessagesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Messages.
        /// </summary>
        public static string rs_ServiceMessagesListShort {
            get {
                return ResourceManager.GetString("rs_ServiceMessagesListShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string rs_Warning {
            get {
                return ResourceManager.GetString("rs_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document_{0}.zip.
        /// </summary>
        public static string rs_ZIPDocumentDefaultName {
            get {
                return ResourceManager.GetString("rs_ZIPDocumentDefaultName", resourceCulture);
            }
        }
    }
}
