//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuronExportedDocuments.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceMessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceMessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuronExportedDocuments.Resources.ServiceMessagesResources", typeof(ServiceMessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning message for an opened document.
        /// </summary>
        public static string rs_DefGetDocumentWarningDisplayName {
            get {
                return ResourceManager.GetString("rs_DefGetDocumentWarningDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your document will be acessiable until &lt;strong&gt;[@DOCINFO_ACCESSFINALDATE]&lt;/strong&gt;.
        /// </summary>
        public static string rs_DefGetDocumentWarningMessage {
            get {
                return ResourceManager.GetString("rs_DefGetDocumentWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main &quot;Hello&quot; message.
        /// </summary>
        public static string rs_DefHomeIndexHelloDescriptionDisplayName {
            get {
                return ResourceManager.GetString("rs_DefHomeIndexHelloDescriptionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get your document input the document&apos;s id and password and press &quot;Get&quot; button..
        /// </summary>
        public static string rs_DefHomeIndexHelloDescriptionMessage {
            get {
                return ResourceManager.GetString("rs_DefHomeIndexHelloDescriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main &quot;Hello&quot; caption.
        /// </summary>
        public static string rs_DefHomeIndexHelloDisplayName {
            get {
                return ResourceManager.GetString("rs_DefHomeIndexHelloDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        public static string rs_DefHomeIndexHelloMessage {
            get {
                return ResourceManager.GetString("rs_DefHomeIndexHelloMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        ///You have a new Neuron document.
        ///To get a document go to page:  [@SETT_GETDOCUMENTURL]
        ///Your document ID: &quot;[@DOC_PUBLISHID]&quot;, document pass: &quot;[@DOC_PUBLISHPASSWORD]&quot;
        ///
        ///For more information about our clinic go to the page: [@SETT_MAINSITEURL]
        ///If you have any problems, write to our support: [@SETT_SUPPORTEMAIL].
        /// </summary>
        public static string rs_DefSendCredentialsEmailMessage {
            get {
                return ResourceManager.GetString("rs_DefSendCredentialsEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template for Emails to users with credential information.
        /// </summary>
        public static string rs_DefSendCredentialsEmailMessageDisplayName {
            get {
                return ResourceManager.GetString("rs_DefSendCredentialsEmailMessageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new Neuron document.
        /// </summary>
        public static string rs_DefSendCredentialsEmailSubject {
            get {
                return ResourceManager.GetString("rs_DefSendCredentialsEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption for Emails to users with credential information.
        /// </summary>
        public static string rs_DefSendCredentialsEmailSubjectDisplayName {
            get {
                return ResourceManager.GetString("rs_DefSendCredentialsEmailSubjectDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL adress for getting the Neuron Document from the configuration file.
        /// </summary>
        public static string rs_GeneralSettingsGetDocumentUrlKeyInfo {
            get {
                return ResourceManager.GetString("rs_GeneralSettingsGetDocumentUrlKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main site&apos;s URL from the configuration file.
        /// </summary>
        public static string rs_GeneralSettingsMainSiteUrlKeyInfo {
            get {
                return ResourceManager.GetString("rs_GeneralSettingsMainSiteUrlKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The support&apos;s EMail adress from the configuration file.
        /// </summary>
        public static string rs_GeneralSupportEmailKeyInfo {
            get {
                return ResourceManager.GetString("rs_GeneralSupportEmailKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        public static string rs_NotSet {
            get {
                return ResourceManager.GetString("rs_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count of days while an user&apos;s document is enabled to download.
        /// </summary>
        public static string rs_ServiceDocumentAccessDaysCountKeyInfo {
            get {
                return ResourceManager.GetString("rs_ServiceDocumentAccessDaysCountKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final date while an user&apos;s document is enabled to download.
        /// </summary>
        public static string rs_ServiceDocumentAccessFinalDateKeyInfo {
            get {
                return ResourceManager.GetString("rs_ServiceDocumentAccessFinalDateKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A date, when the document was created.
        /// </summary>
        public static string rs_ServiceDocumentCreatDateKeyInfo {
            get {
                return ResourceManager.GetString("rs_ServiceDocumentCreatDateKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail for delivery document&apos;s credentials.
        /// </summary>
        public static string rs_ServiceDocumentDeliveryEmailKeyInfo {
            get {
                return ResourceManager.GetString("rs_ServiceDocumentDeliveryEmailKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A phone number for delivery document&apos;s credentials.
        /// </summary>
        public static string rs_ServiceDocumentDeliveryPhoneKeyInfo {
            get {
                return ResourceManager.GetString("rs_ServiceDocumentDeliveryPhoneKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A date, when the document was created.
        /// </summary>
        public static string rs_ServiceDocumentInfoCreatDateKeyInfo {
            get {
                return ResourceManager.GetString("rs_ServiceDocumentInfoCreatDateKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A date, when the document was opened for the first time (or &quot;Not set&quot;).
        /// </summary>
        public static string rs_ServiceDocumentInfoOpenDateKeyInfo {
            get {
                return ResourceManager.GetString("rs_ServiceDocumentInfoOpenDateKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document&apos;s access ID.
        /// </summary>
        public static string rs_ServiceDocumentInfoPublishIdKeyInfo {
            get {
                return ResourceManager.GetString("rs_ServiceDocumentInfoPublishIdKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A status of the document.
        /// </summary>
        public static string rs_ServiceDocumentInfoStatusKeyInfo {
            get {
                return ResourceManager.GetString("rs_ServiceDocumentInfoStatusKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document&apos;s name.
        /// </summary>
        public static string rs_ServiceDocumentNameKeyInfo {
            get {
                return ResourceManager.GetString("rs_ServiceDocumentNameKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A date, when the document was opened for the first time (or &quot;Not set&quot;).
        /// </summary>
        public static string rs_ServiceDocumentOpenDateKeyInfo {
            get {
                return ResourceManager.GetString("rs_ServiceDocumentOpenDateKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document&apos;s access ID.
        /// </summary>
        public static string rs_ServiceDocumentPublishIdKeyInfo {
            get {
                return ResourceManager.GetString("rs_ServiceDocumentPublishIdKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document&apos;s password.
        /// </summary>
        public static string rs_ServiceDocumentPublishPasswordKeyInfo {
            get {
                return ResourceManager.GetString("rs_ServiceDocumentPublishPasswordKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A status of the document.
        /// </summary>
        public static string rs_ServiceDocumentStatusKeyInfo {
            get {
                return ResourceManager.GetString("rs_ServiceDocumentStatusKeyInfo", resourceCulture);
            }
        }
    }
}
