//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuronExportedDocuments.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuronExportedDocuments.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned.
        /// </summary>
        public static string rs_DocumentLogOperationTypeBanned {
            get {
                return ResourceManager.GetString("rs_DocumentLogOperationTypeBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail Access.
        /// </summary>
        public static string rs_DocumentLogOperationTypeFailAccess {
            get {
                return ResourceManager.GetString("rs_DocumentLogOperationTypeFailAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported.
        /// </summary>
        public static string rs_DocumentLogOperationTypeImported {
            get {
                return ResourceManager.GetString("rs_DocumentLogOperationTypeImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Sent To User.
        /// </summary>
        public static string rs_DocumentLogOperationTypeInfoSentedToUser {
            get {
                return ResourceManager.GetString("rs_DocumentLogOperationTypeInfoSentedToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string rs_DocumentLogOperationTypePublished {
            get {
                return ResourceManager.GetString("rs_DocumentLogOperationTypePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Republished.
        /// </summary>
        public static string rs_DocumentLogOperationTypeRepublished {
            get {
                return ResourceManager.GetString("rs_DocumentLogOperationTypeRepublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetToArchive.
        /// </summary>
        public static string rs_DocumentLogOperationTypeSetToArchive {
            get {
                return ResourceManager.GetString("rs_DocumentLogOperationTypeSetToArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Access.
        /// </summary>
        public static string rs_DocumentLogOperationTypeSuccessAccess {
            get {
                return ResourceManager.GetString("rs_DocumentLogOperationTypeSuccessAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblocked By Admin.
        /// </summary>
        public static string rs_DocumentLogOperationTypeUnblockedByAdmin {
            get {
                return ResourceManager.GetString("rs_DocumentLogOperationTypeUnblockedByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Error Value!.
        /// </summary>
        public static string rs_ExportedDocStatusErrorValue {
            get {
                return ResourceManager.GetString("rs_ExportedDocStatusErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Archive.
        /// </summary>
        public static string rs_ExportedDocStatusInArchive {
            get {
                return ResourceManager.GetString("rs_ExportedDocStatusInArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Sent.
        /// </summary>
        public static string rs_ExportedDocStatusInfoSented {
            get {
                return ResourceManager.GetString("rs_ExportedDocStatusInfoSented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string rs_ExportedDocStatusPublished {
            get {
                return ResourceManager.GetString("rs_ExportedDocStatusPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled.
        /// </summary>
        public static string rs_ExportedDocStatusUnhandled {
            get {
                return ResourceManager.GetString("rs_ExportedDocStatusUnhandled", resourceCulture);
            }
        }
    }
}
