//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuronExportedDocuments.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidateMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidateMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuronExportedDocuments.Resources.ValidateMessages", typeof(ValidateMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors in captcha system. Message: &quot;{0}&quot;.
        /// </summary>
        public static string rs_CaptchaError {
            get {
                return ResourceManager.GetString("rs_CaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha error occured. Please try again.
        /// </summary>
        public static string rs_CaptchaErrorOccured {
            get {
                return ResourceManager.GetString("rs_CaptchaErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response parameter is invalid or malformed..
        /// </summary>
        public static string rs_CaptchaErrorResponseParameterInvalid {
            get {
                return ResourceManager.GetString("rs_CaptchaErrorResponseParameterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response parameter is missing..
        /// </summary>
        public static string rs_CaptchaErrorResponseParameterMissing {
            get {
                return ResourceManager.GetString("rs_CaptchaErrorResponseParameterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The secret parameter is invalid or malformed..
        /// </summary>
        public static string rs_CaptchaErrorSecretParameterIsInvalid {
            get {
                return ResourceManager.GetString("rs_CaptchaErrorSecretParameterIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The secret parameter is missing..
        /// </summary>
        public static string rs_CaptchaErrorSecretParameterIsMissing {
            get {
                return ResourceManager.GetString("rs_CaptchaErrorSecretParameterIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Unknown captcha error..
        /// </summary>
        public static string rs_CaptchaErrorUnknown {
            get {
                return ResourceManager.GetString("rs_CaptchaErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The captcha check is fail. Please try again.
        /// </summary>
        public static string rs_CaptchaErrorValue {
            get {
                return ResourceManager.GetString("rs_CaptchaErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document ID must has not more than 12 characters.
        /// </summary>
        public static string rs_DocumentIdMustBe12 {
            get {
                return ResourceManager.GetString("rs_DocumentIdMustBe12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document ID must be set.
        /// </summary>
        public static string rs_DocumentIdMustBeSet {
            get {
                return ResourceManager.GetString("rs_DocumentIdMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document ID must contains only digits.
        /// </summary>
        public static string rs_DocumentIdOnlyDigits {
            get {
                return ResourceManager.GetString("rs_DocumentIdOnlyDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Document ID or Password are incorrect.
        /// </summary>
        public static string rs_DocumentIdOrPasswordAreIncorrect {
            get {
                return ResourceManager.GetString("rs_DocumentIdOrPasswordAreIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document access period has been expired.
        /// </summary>
        public static string rs_DocumentIsInArchive {
            get {
                return ResourceManager.GetString("rs_DocumentIsInArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credential data for the document is not valid.
        /// </summary>
        public static string rs_DocumentIsNotValid {
            get {
                return ResourceManager.GetString("rs_DocumentIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Password must has not more than 8 characters.
        /// </summary>
        public static string rs_DocumentPasswordMustBe8 {
            get {
                return ResourceManager.GetString("rs_DocumentPasswordMustBe8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Password must be set.
        /// </summary>
        public static string rs_DocumentPasswordMustBeSet {
            get {
                return ResourceManager.GetString("rs_DocumentPasswordMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the document&apos;s password.
        /// </summary>
        public static string rs_DocumentPleaseEnterPassword {
            get {
                return ResourceManager.GetString("rs_DocumentPleaseEnterPassword", resourceCulture);
            }
        }
    }
}
